### ISSUE TITLE
specrectify

### ISSUE THREAD

**Issue by hlabathems** [crawfordsm/zSALT#17]
Traceback (most recent call last):
  File "../zSALT/zsalt/reducedata.py", line 31, in <module>
    specred(infile_list, propid, inter=True, guessfile=None)
  File "/Users/michaelhlabathe/zSALT/zsalt/specred.py", line 90, in specred
    blank=0.0, nearest=True, clobber=True, logfile=logfile, verbose=True)
  File "/Users/michaelhlabathe/iraf/pysalt/saltspec/specrectify.py", line 110, in specrectify
    clobber=clobber, log=log, verbose=verbose)
  File "/Users/michaelhlabathe/iraf/pysalt/saltspec/specrectify.py", line 181, in rectify
    slit, xbin, ybin, slitid, function, order)
  File "/Users/michaelhlabathe/iraf/pysalt/saltspec/specrectify.py", line 355, in findsol
    soldict, y_i, nearest, timeobs, exptime, instrume, grating, grang, arang, filtername, slitid, xarr)
  File "/Users/michaelhlabathe/iraf/pysalt/saltspec/specrectify.py", line 488, in findlinesol
    domain = order_list[domain]
UnboundLocalError: local variable 'domain' referenced before assignment

**Comment by crawfordsm** [comment]
Thanks for the feedback @hlabathems -- can you update your pysalt to the most recent version?

**Comment by hlabathems** [comment]
I updated pysalt first before running reducedata.py

On 2017-04-25 12:32, Steve Crawford wrote:

> Thanks for the feedback @hlabathems [1] -- can you update your pysalt to the most recent version? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/hlabathems
[2] https://github.com/crawfordsm/zSALT/issues/17#issuecomment-296989460
[3]
